"use client"

import { useState } from "react"
import { MapPin, Phone, Clock, CheckCircle2, Navigation, Search } from "lucide-react"

interface Office {
  id: string
  name: string
  address: string
  distance_km: number
  travel_minutes: number
  hours: string
  is_open: boolean
  phone: string
  what_to_carry: string[]
  cost_estimate: string
}

const OFFICES: Office[] = [
  {
    id: "o1",
    name: "High Court Civil & Consumer Notary Services",
    address: "High Court Buildings, Rajaji Salai, Chennai – 600 104",
    distance_km: 0.8,
    travel_minutes: 12,
    hours: "Mon–Sat 10:00 AM – 5:30 PM",
    is_open: true,
    phone: "+91 44 2534 1234",
    what_to_carry: ["Original Aadhaar card", "Draft affidavit (generated by Urimai)", "₹200–₹500 fee"],
    cost_estimate: "₹200–₹500",
  },
  {
    id: "o2",
    name: "George Town Legal Notary Public",
    address: "14, Mint Street, George Town, Chennai – 600 001",
    distance_km: 1.4,
    travel_minutes: 18,
    hours: "Mon–Sat 9:30 AM – 6:00 PM",
    is_open: true,
    phone: "+91 44 2522 5678",
    what_to_carry: ["Original Aadhaar card", "Draft affidavit", "₹150–₹400 fee"],
    cost_estimate: "₹150–₹400",
  },
  {
    id: "o3",
    name: "Egmore Sub-Registrar Office",
    address: "Egmore Government Complex, Chennai – 600 008",
    distance_km: 2.3,
    travel_minutes: 25,
    hours: "Mon–Fri 10:00 AM – 5:00 PM",
    is_open: false,
    phone: "+91 44 2819 3456",
    what_to_carry: ["Original Aadhaar card", "Draft affidavit", "₹100–₹300 fee"],
    cost_estimate: "₹100–₹300",
  },
]

export function OfficeNavigatorView() {
  const [radius, setRadius] = useState<10 | 20>(10)
  const [visited, setVisited] = useState<Record<string, boolean>>({})
  const [pincode, setPincode] = useState("600001")

  const visible = OFFICES.filter((o) => o.distance_km <= radius)

  return (
    <div className="flex flex-col gap-6">
      {/* Search controls */}
      <section className="rounded-xl border border-softborder bg-card p-5">
        <div className="flex flex-wrap items-end gap-4">
          <div className="flex-1">
            <label className="mb-1.5 block text-sm font-semibold text-ink-900">Your location (pincode)</label>
            <div className="flex items-center rounded-md border border-softborder bg-card focus-within:border-ink-800 focus-within:ring-2 focus-within:ring-ink-900/10">
              <MapPin className="ml-3 h-4 w-4 shrink-0 text-muted-foreground" />
              <input
                value={pincode}
                onChange={(e) => setPincode(e.target.value.replace(/\D/g, "").slice(0, 6))}
                placeholder="600001"
                className="w-full bg-transparent px-3 py-2.5 text-sm text-ink-900 outline-none"
              />
            </div>
          </div>
          <div>
            <label className="mb-1.5 block text-sm font-semibold text-ink-900">Search radius</label>
            <div className="flex overflow-hidden rounded-md border border-softborder" role="group">
              {([10, 20] as const).map((r) => (
                <button key={r} type="button" onClick={() => setRadius(r)}
                  className={`px-4 py-2.5 text-sm font-semibold transition-colors ${
                    radius === r ? "bg-ink-900 text-parchment" : "bg-card text-ink-700 hover:bg-bluesoft"
                  }`}>
                  {r} km
                </button>
              ))}
            </div>
          </div>
          <button type="button"
            className="inline-flex items-center gap-1.5 rounded-md bg-ink-900 px-4 py-2.5 text-sm font-semibold text-parchment transition-colors hover:bg-ink-800">
            <Search className="h-4 w-4" />
            Search
          </button>
        </div>
        <p className="mt-3 text-xs text-muted-foreground">
          GPS location: Chennai {pincode} · Geocoding API validated · {visible.length} offices found within {radius} km
        </p>
      </section>

      {/* Office cards */}
      <div className="flex flex-col gap-4">
        {visible.map((office) => (
          <div key={office.id} className={`rounded-xl border p-5 ${
            visited[office.id] ? "border-forest/30 bg-forest-soft" : "border-softborder bg-card"
          }`}>
            <div className="flex flex-wrap items-start justify-between gap-3">
              <div>
                <p className="font-serif text-base font-bold text-ink-900">{office.name}</p>
                <p className="mt-0.5 text-sm text-ink-700">{office.address}</p>
              </div>
              <span className={`shrink-0 rounded-md border px-2.5 py-1 text-xs font-bold ${
                office.is_open
                  ? "border-forest/20 bg-forest-soft text-forest"
                  : "border-softborder bg-card text-muted-foreground"
              }`}>
                {office.is_open ? "● Open now" : "● Closed"}
              </span>
            </div>

            <div className="mt-3 flex flex-wrap gap-3 text-xs text-ink-700">
              <span className="flex items-center gap-1">
                <MapPin className="h-3.5 w-3.5 text-amber-ink" />
                {office.distance_km} km · {office.travel_minutes} min transit
              </span>
              <span className="flex items-center gap-1">
                <Clock className="h-3.5 w-3.5 text-amber-ink" />
                {office.hours}
              </span>
              <span className="flex items-center gap-1">
                <Phone className="h-3.5 w-3.5 text-amber-ink" />
                {office.phone}
              </span>
            </div>

            <div className="mt-4 rounded-lg border border-softborder bg-parchment px-4 py-3">
              <p className="mb-2 text-xs font-semibold uppercase tracking-wide text-ink-700">What to carry</p>
              <ul className="flex flex-col gap-1">
                {office.what_to_carry.map((item, i) => (
                  <li key={i} className="flex items-start gap-2 text-xs text-ink-800">
                    <span className="mt-0.5 h-1.5 w-1.5 shrink-0 rounded-full bg-amber-ink" />
                    {item}
                  </li>
                ))}
              </ul>
              <p className="mt-2 text-xs font-semibold text-amber-ink">Estimated cost: {office.cost_estimate}</p>
            </div>

            <div className="mt-4 flex flex-wrap gap-2">
              <a
                href={`tel:${office.phone}`}
                className="inline-flex items-center gap-1.5 rounded-md border border-softborder px-3 py-2 text-xs font-semibold text-ink-900 transition-colors hover:bg-bluesoft"
              >
                <Phone className="h-3.5 w-3.5" />
                Call office
              </a>
              <a
                href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(office.name + " " + office.address)}`}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-1.5 rounded-md border border-softborder px-3 py-2 text-xs font-semibold text-ink-900 transition-colors hover:bg-bluesoft"
              >
                <Navigation className="h-3.5 w-3.5" />
                Navigate in Google Maps
              </a>
              {!visited[office.id] ? (
                <button
                  type="button"
                  onClick={() => setVisited((prev) => ({ ...prev, [office.id]: true }))}
                  className="inline-flex items-center gap-1.5 rounded-md bg-forest px-3 py-2 text-xs font-semibold text-parchment transition-colors hover:opacity-90"
                >
                  <CheckCircle2 className="h-3.5 w-3.5" />
                  I have visited & collected document
                </button>
              ) : (
                <span className="inline-flex items-center gap-1.5 rounded-md bg-forest-soft px-3 py-2 text-xs font-semibold text-forest">
                  <CheckCircle2 className="h-3.5 w-3.5" />
                  Visit logged — upload document now
                </span>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}
