"use client"

import { useState } from "react"
import { useRouter } from "next/navigation"
import {
  FileText, Download, CheckCircle2, ArrowRight, Loader2, Eye,
  AlertCircle, MapPin, Clock, Phone, Navigation, ChevronDown, ChevronUp, Upload,
} from "lucide-react"
import { useCaseContext } from "@/lib/case-context"

// ─── Required evidence documents the user must physically have ────────────────

interface RequiredDoc {
  id: string
  name: string
  description: string
  examples: string
  office: {
    name: string
    address: string
    hours: string
    phone: string
    what_to_carry: string[]
    maps_query: string
  } | null
}

const REQUIRED_DOCS: RequiredDoc[] = [
  {
    id: "r1",
    name: "Purchase Invoice / Receipt",
    description: "Original bill or e-invoice showing the product/service, price, date, and seller details.",
    examples: "Amazon order invoice, shop receipt, GST bill",
    office: null, // digital — no office needed
  },
  {
    id: "r2",
    name: "Legal Notice sent to Opposite Party",
    description: "Copy of the legal notice you sent demanding remedy, with proof of dispatch (speed post receipt or courier tracking).",
    examples: "Registered post receipt, courier AWB, email with read-receipt",
    office: null,
  },
  {
    id: "r3",
    name: "Opposite Party's Reply (if any)",
    description: "Any written response, email, or letter received from the company. If no reply, a declaration of non-response is sufficient.",
    examples: "Company email, WhatsApp screenshot, rejection letter",
    office: null,
  },
  {
    id: "r4",
    name: "Affidavit (Notarised)",
    description: "A sworn statement on stamp paper verifying the facts of your complaint. Must be signed before a Notary Public.",
    examples: "Notarised affidavit on ₹20 stamp paper",
    office: {
      name: "High Court Civil & Consumer Notary Services",
      address: "High Court Buildings, Rajaji Salai, Chennai – 600 104",
      hours: "Mon–Sat  10:00 AM – 5:30 PM",
      phone: "+91 44 2534 1234",
      what_to_carry: [
        "Original Aadhaar card (for identity verification)",
        "Printed draft affidavit (generated by Urimai — download below)",
        "₹200–₹500 notary fee in cash",
        "₹20 stamp paper (available at the notary counter)",
      ],
      maps_query: "High Court Notary Services Rajaji Salai Chennai",
    },
  },
  {
    id: "r5",
    name: "Court Fee (Demand Draft / Online)",
    description: "Filing fee payable to the District Consumer Commission. For claims up to ₹5 lakh the fee is ₹200.",
    examples: "DD in favour of 'DCDRC Chennai', or eDaakhil online payment",
    office: {
      name: "State Bank of India — High Court Branch",
      address: "High Court Campus, Rajaji Salai, Chennai – 600 104",
      hours: "Mon–Fri  10:00 AM – 4:00 PM",
      phone: "+91 44 2534 5678",
      what_to_carry: [
        "Aadhaar / PAN card",
        "Cash or debit card for ₹200 DD charges",
        "DD payable to: 'DCDRC Chennai'",
      ],
      maps_query: "State Bank of India High Court Branch Chennai",
    },
  },
]

// ─── AI-generated documents (ready to download) ───────────────────────────────

const GENERATED_DOCS = [
  {
    id: "d1",
    name: "Complaint Petition",
    pages: 4,
    description: "Formal complaint under Section 35 of the Consumer Protection Act, 2019.",
  },
  {
    id: "d2",
    name: "Affidavit of Complainant",
    pages: 2,
    description: "Sworn statement verifying the facts — take this to the notary for signing.",
  },
  {
    id: "d3",
    name: "Evidence Index",
    pages: 1,
    description: "Numbered list of all supporting documents: invoice, chats, photos.",
  },
  {
    id: "d4",
    name: "Vakalatnama",
    pages: 1,
    description: "Power of attorney — not required for self-represented complainants.",
  },
]

const PREVIEW_TEXT = `IN THE DISTRICT CONSUMER DISPUTES REDRESSAL COMMISSION
CHENNAI

Complaint No. ___/2024

IN THE MATTER OF:

Ravi Kumar
S/o [Father's Name], aged [Age] years,
R/o [Address], Chennai – [Pincode], Tamil Nadu.
                                        ...COMPLAINANT

VERSUS

QuickMart Electronics Pvt. Ltd.
Registered Office: [Address]
                                        ...OPPOSITE PARTY

COMPLAINT UNDER SECTION 35 OF THE
CONSUMER PROTECTION ACT, 2019

MOST RESPECTFULLY SHOWETH:

1. That the Complainant is a consumer as defined under Section 2(7) of the Consumer Protection Act, 2019, having purchased a Samsung Galaxy S23 smartphone from the Opposite Party on 15.09.2024 for a consideration of ₹45,000/- (Rupees Forty-Five Thousand Only) for personal use.

2. That the said product developed a defect within 10 days of purchase, rendering it non-functional. The Complainant duly notified the Opposite Party, who refused to repair, replace, or refund the product, constituting a clear deficiency in service and unfair trade practice.

3. That the cause of action arose on 25.09.2024 and is within the limitation period prescribed under Section 69 of the Act.

PRAYER:
In view of the above, it is most respectfully prayed that this Hon'ble Commission may be pleased to:
(a) Direct the Opposite Party to refund ₹45,000/- with interest @ 12% p.a.;
(b) Award compensation of ₹5,000/- for mental agony and harassment;
(c) Award costs of litigation.`

// ─── Component ────────────────────────────────────────────────────────────────

export function DocumentBuilder() {
  const router = useRouter()
  const { caseData } = useCaseContext()

  // per required-doc: true = have it, false = don't have it, undefined = not answered
  const [haveDoc, setHaveDoc] = useState<Record<string, boolean>>({})
  // which "don't have" panels are expanded
  const [expanded, setExpanded] = useState<Record<string, boolean>>({})
  // generated doc preview
  const [preview, setPreview] = useState<string | null>(null)
  const [submitting, setSubmitting] = useState(false)

  const allAnswered = REQUIRED_DOCS.every((d) => haveDoc[d.id] !== undefined)
  const missingCount = REQUIRED_DOCS.filter((d) => haveDoc[d.id] === false).length

  function toggleHave(id: string, value: boolean) {
    setHaveDoc((prev) => ({ ...prev, [id]: value }))
    if (!value) setExpanded((prev) => ({ ...prev, [id]: true }))
    else setExpanded((prev) => ({ ...prev, [id]: false }))
  }

  function toggleExpand(id: string) {
    setExpanded((prev) => ({ ...prev, [id]: !prev[id] }))
  }

  async function handleProceed() {
    setSubmitting(true)
    await new Promise((r) => setTimeout(r, 700))
    router.push("/filing")
  }

  // Use commission address from context if available, else fallback
  const commissionAddress =
    caseData.commission_address || "Singaravelar Maligai, Rajaji Salai, Chennai – 600 001"
  const commissionName =
    caseData.commission_full_name || "District Consumer Disputes Redressal Commission, Chennai"

  return (
    <div className="flex flex-col gap-8">

      {/* ── Section 1: Required documents checklist ── */}
      <section className="rounded-xl border border-softborder bg-card p-5 md:p-6">
        <div className="mb-1 flex items-center gap-2">
          <h2 className="font-serif text-lg font-bold text-ink-900">Documents you need to arrange</h2>
          {missingCount > 0 && (
            <span className="rounded-md bg-danger-ink px-2 py-0.5 text-[10px] font-bold text-parchment">
              {missingCount} missing
            </span>
          )}
        </div>
        <p className="mb-5 text-xs text-muted-foreground">
          Mark each document. If you don&apos;t have one, we&apos;ll show you exactly where to get it.
        </p>

        <div className="flex flex-col gap-4">
          {REQUIRED_DOCS.map((doc) => {
            const have = haveDoc[doc.id]
            const isExpanded = expanded[doc.id]

            return (
              <div
                key={doc.id}
                className={`rounded-lg border transition-colors ${
                  have === true
                    ? "border-forest/30 bg-forest-soft"
                    : have === false
                    ? "border-danger-ink/30 bg-red-50"
                    : "border-softborder bg-card"
                }`}
              >
                {/* Doc header */}
                <div className="flex items-start gap-3 p-4">
                  <FileText
                    className={`mt-0.5 h-5 w-5 shrink-0 ${
                      have === true ? "text-forest" : have === false ? "text-danger-ink" : "text-amber-ink"
                    }`}
                  />
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-semibold text-ink-900">{doc.name}</p>
                    <p className="mt-0.5 text-xs text-muted-foreground">{doc.description}</p>
                    <p className="mt-1 text-xs text-ink-700">
                      <span className="font-medium">Examples: </span>{doc.examples}
                    </p>

                    {/* Have / Don't have toggle */}
                    <div className="mt-3 flex flex-wrap gap-2">
                      <button
                        type="button"
                        onClick={() => toggleHave(doc.id, true)}
                        className={`inline-flex items-center gap-1.5 rounded-md border px-3 py-1.5 text-xs font-semibold transition-colors ${
                          have === true
                            ? "border-forest bg-forest text-parchment"
                            : "border-softborder bg-card text-ink-700 hover:bg-bluesoft"
                        }`}
                      >
                        <CheckCircle2 className="h-3.5 w-3.5" />
                        I have this
                      </button>
                      <button
                        type="button"
                        onClick={() => toggleHave(doc.id, false)}
                        className={`inline-flex items-center gap-1.5 rounded-md border px-3 py-1.5 text-xs font-semibold transition-colors ${
                          have === false
                            ? "border-danger-ink bg-danger-ink text-parchment"
                            : "border-softborder bg-card text-ink-700 hover:bg-bluesoft"
                        }`}
                      >
                        <AlertCircle className="h-3.5 w-3.5" />
                        I don&apos;t have this
                      </button>
                    </div>
                  </div>

                  {/* Expand toggle for missing docs */}
                  {have === false && doc.office && (
                    <button
                      type="button"
                      onClick={() => toggleExpand(doc.id)}
                      className="shrink-0 rounded-md border border-softborder p-1.5 text-ink-700 hover:bg-bluesoft"
                      aria-label="Toggle office details"
                    >
                      {isExpanded ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}
                    </button>
                  )}
                </div>

                {/* ── Inline office + Google Maps panel ── */}
                {have === false && doc.office && isExpanded && (
                  <div className="border-t border-softborder mx-4 mb-4 pt-4">
                    <p className="mb-3 text-xs font-bold uppercase tracking-wide text-danger-ink">
                      Where to get this document
                    </p>

                    {/* Office card */}
                    <div className="rounded-lg border border-softborder bg-parchment p-4">
                      <div className="flex items-start gap-2">
                        <MapPin className="mt-0.5 h-4 w-4 shrink-0 text-amber-ink" />
                        <div className="flex-1 min-w-0">
                          <p className="text-sm font-semibold text-ink-900">{doc.office.name}</p>
                          <p className="mt-0.5 text-xs text-ink-700">{doc.office.address}</p>
                          <div className="mt-2 flex flex-wrap gap-3 text-xs text-ink-700">
                            <span className="flex items-center gap-1">
                              <Clock className="h-3.5 w-3.5 text-amber-ink" />
                              {doc.office.hours}
                            </span>
                            <span className="flex items-center gap-1">
                              <Phone className="h-3.5 w-3.5 text-amber-ink" />
                              {doc.office.phone}
                            </span>
                          </div>
                        </div>
                      </div>

                      {/* What to carry */}
                      <div className="mt-3 rounded-md border border-softborder bg-card px-3 py-2.5">
                        <p className="mb-1.5 text-[10px] font-bold uppercase tracking-wide text-ink-700">
                          What to carry
                        </p>
                        <ul className="flex flex-col gap-1">
                          {doc.office.what_to_carry.map((item, i) => (
                            <li key={i} className="flex items-start gap-2 text-xs text-ink-800">
                              <span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-amber-ink" />
                              {item}
                            </li>
                          ))}
                        </ul>
                      </div>

                      {/* Google Maps prompt */}
                      <div className="mt-3 rounded-md border border-amber-ink/30 bg-amber-soft px-3 py-2.5">
                        <p className="mb-1 text-[10px] font-bold uppercase tracking-wide text-amber-ink">
                          Google Maps — ready prompt
                        </p>
                        <p className="mb-2 font-mono text-xs text-ink-800 break-all">
                          &quot;{doc.office.maps_query}&quot;
                        </p>
                        <a
                          href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(doc.office.maps_query)}`}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="inline-flex items-center gap-1.5 rounded-md bg-ink-900 px-3 py-2 text-xs font-semibold text-parchment transition-colors hover:bg-ink-800"
                        >
                          <Navigation className="h-3.5 w-3.5" />
                          Open in Google Maps
                        </a>
                      </div>
                    </div>

                    {/* Upload slot once they return */}
                    <div className="mt-3 flex items-center gap-3 rounded-lg border border-dashed border-softborder bg-card px-4 py-3">
                      <Upload className="h-4 w-4 shrink-0 text-muted-foreground" />
                      <div className="flex-1 min-w-0">
                        <p className="text-xs font-semibold text-ink-900">Upload once collected</p>
                        <p className="text-[11px] text-muted-foreground">
                          Come back here after your visit and upload the scanned copy.
                        </p>
                      </div>
                      <label className="shrink-0 cursor-pointer rounded-md border border-softborder bg-card px-3 py-1.5 text-xs font-semibold text-ink-700 transition-colors hover:bg-bluesoft">
                        Choose file
                        <input type="file" accept="image/*,.pdf" className="sr-only" />
                      </label>
                    </div>
                  </div>
                )}

                {/* No-office missing doc (digital) */}
                {have === false && !doc.office && (
                  <div className="border-t border-softborder mx-4 mb-4 pt-3">
                    <p className="text-xs text-ink-700">
                      <span className="font-semibold">Tip: </span>
                      Check your email inbox, WhatsApp, or the seller&apos;s app for a digital copy.
                      Screenshot or export as PDF and upload below.
                    </p>
                    <div className="mt-3 flex items-center gap-3 rounded-lg border border-dashed border-softborder bg-card px-4 py-3">
                      <Upload className="h-4 w-4 shrink-0 text-muted-foreground" />
                      <div className="flex-1 min-w-0">
                        <p className="text-xs font-semibold text-ink-900">Upload document</p>
                        <p className="text-[11px] text-muted-foreground">PDF, JPG, or PNG · max 5 MB</p>
                      </div>
                      <label className="shrink-0 cursor-pointer rounded-md border border-softborder bg-card px-3 py-1.5 text-xs font-semibold text-ink-700 transition-colors hover:bg-bluesoft">
                        Choose file
                        <input type="file" accept="image/*,.pdf" className="sr-only" />
                      </label>
                    </div>
                  </div>
                )}
              </div>
            )
          })}
        </div>
      </section>

      {/* ── Section 2: Filing office details ── */}
      <section className="rounded-xl border border-softborder bg-card p-5 md:p-6">
        <div className="mb-4 flex items-center gap-2">
          <MapPin className="h-5 w-5 text-forest" />
          <h2 className="font-serif text-lg font-bold text-ink-900">Where to file your complaint</h2>
        </div>

        <div className="rounded-lg border border-forest/30 bg-forest-soft p-4">
          <p className="text-sm font-semibold text-ink-900">{commissionName}</p>
          <p className="mt-0.5 text-xs text-ink-700">{commissionAddress}</p>
          <div className="mt-2 flex flex-wrap gap-3 text-xs text-ink-700">
            <span className="flex items-center gap-1">
              <Clock className="h-3.5 w-3.5 text-forest" />
              Mon–Fri  10:30 AM – 5:00 PM
            </span>
            <span className="flex items-center gap-1">
              <Phone className="h-3.5 w-3.5 text-forest" />
              +91 44 2534 0000
            </span>
          </div>

          {/* Google Maps prompt for the commission */}
          <div className="mt-3 rounded-md border border-amber-ink/30 bg-amber-soft px-3 py-2.5">
            <p className="mb-1 text-[10px] font-bold uppercase tracking-wide text-amber-ink">
              Google Maps — ready prompt
            </p>
            <p className="mb-2 font-mono text-xs text-ink-800">
              &quot;District Consumer Disputes Redressal Commission Chennai Singaravelar Maligai&quot;
            </p>
            <a
              href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(
                "District Consumer Disputes Redressal Commission Chennai Singaravelar Maligai Rajaji Salai"
              )}`}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1.5 rounded-md bg-ink-900 px-3 py-2 text-xs font-semibold text-parchment transition-colors hover:bg-ink-800"
            >
              <Navigation className="h-3.5 w-3.5" />
              Open in Google Maps
            </a>
          </div>

          <div className="mt-3 rounded-md border border-softborder bg-card px-3 py-2.5">
            <p className="mb-1.5 text-[10px] font-bold uppercase tracking-wide text-ink-700">
              What to carry to the commission
            </p>
            <ul className="flex flex-col gap-1">
              {[
                "3 sets of the complete complaint (petition + affidavit + evidence index)",
                "Original documents + 3 photocopies of each",
                "Court fee DD / eDaakhil payment receipt",
                "Aadhaar card (original + photocopy)",
              ].map((item, i) => (
                <li key={i} className="flex items-start gap-2 text-xs text-ink-800">
                  <span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-forest" />
                  {item}
                </li>
              ))}
            </ul>
          </div>
        </div>
      </section>

      {/* ── Section 3: AI-generated documents ── */}
      <section className="rounded-xl border border-softborder bg-card p-5 md:p-6">
        <h2 className="mb-5 font-serif text-lg font-bold text-ink-900">AI-generated documents</h2>
        <div className="flex flex-col gap-3">
          {GENERATED_DOCS.map((doc) => (
            <div key={doc.id} className="flex items-start justify-between gap-4 rounded-lg border border-softborder p-4">
              <div className="flex items-start gap-3">
                <FileText className="mt-0.5 h-5 w-5 shrink-0 text-amber-ink" />
                <div>
                  <p className="text-sm font-semibold text-ink-900">{doc.name}</p>
                  <p className="mt-0.5 text-xs text-muted-foreground">{doc.description}</p>
                  <p className="mt-1 text-xs text-ink-700">
                    {doc.pages} page{doc.pages > 1 ? "s" : ""}
                  </p>
                </div>
              </div>
              <div className="flex shrink-0 items-center gap-2">
                <CheckCircle2 className="h-4 w-4 text-forest" />
                <button
                  type="button"
                  onClick={() => setPreview(preview === doc.id ? null : doc.id)}
                  className="inline-flex items-center gap-1 rounded-md border border-softborder px-2.5 py-1.5 text-xs font-semibold text-ink-700 transition-colors hover:bg-bluesoft"
                >
                  <Eye className="h-3.5 w-3.5" />
                  Preview
                </button>
                <button
                  type="button"
                  onClick={() => typeof window !== "undefined" && window.print()}
                  className="inline-flex items-center gap-1 rounded-md border border-softborder px-2.5 py-1.5 text-xs font-semibold text-ink-700 transition-colors hover:bg-bluesoft"
                >
                  <Download className="h-3.5 w-3.5" />
                  PDF
                </button>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Preview panel */}
      {preview && (
        <section className="rounded-xl border border-softborder bg-card p-5">
          <div className="mb-3 flex items-center justify-between">
            <p className="font-serif text-base font-bold text-ink-900">
              {GENERATED_DOCS.find((d) => d.id === preview)?.name} — Preview
            </p>
            <button
              type="button"
              onClick={() => setPreview(null)}
              className="text-xs font-semibold text-muted-foreground hover:text-ink-900"
            >
              Close
            </button>
          </div>
          <pre className="max-h-80 overflow-auto rounded-lg border border-softborder bg-parchment p-4 font-serif text-[11px] leading-relaxed text-ink-900 whitespace-pre-wrap">
            {PREVIEW_TEXT}
          </pre>
        </section>
      )}

      {/* Proceed button */}
      {!allAnswered && (
        <p className="text-xs text-amber-ink font-semibold">
          ↑ Please mark all {REQUIRED_DOCS.length} documents above before proceeding.
        </p>
      )}
      <button
        onClick={handleProceed}
        disabled={submitting || !allAnswered}
        className="inline-flex items-center justify-center gap-2 rounded-md bg-ink-900 px-6 py-3.5 text-sm font-bold text-parchment transition-colors hover:bg-ink-800 disabled:opacity-60"
      >
        {submitting
          ? <><Loader2 className="h-4 w-4 animate-spin" />Preparing filing…</>
          : <>Proceed to e-filing <ArrowRight className="h-4 w-4" /></>}
      </button>
    </div>
  )
}
